In [113]:
import numpy as np
import itertools as it
s = list(it.product(range(2), repeat=8))
# print(s)
len(s)
# type(s[1])
# list(s[1])
origin_list=[]
for i in s:
    origin_list.append(list(i))

len(origin_list)

256

In [114]:
ar=np.array(origin_list)
ar

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1]])

In [115]:
d1=np.ones(ar.shape)
# d1[:][]=100
# d1[0][:]
# for i in range(256):
#     d1[i][0]=100

d1

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [116]:
for i in ar[0]:
    print(i)

0
0
0
0
0
0
0
0


In [117]:
up=1.1
down=1/1.1
for i in range(256):
    for j in range(8):
        if(ar[i][j]==0):
            d1[i][j]=d1[i][j-1]*down
        elif(ar[i][j]==1):
            d1[i][j]=d1[i][j-1]*up

d1

array([[0.90909091, 0.82644628, 0.7513148 , ..., 0.56447393, 0.51315812,
        0.46650738],
       [0.90909091, 0.82644628, 0.7513148 , ..., 0.56447393, 0.51315812,
        0.56447393],
       [0.90909091, 0.82644628, 0.7513148 , ..., 0.56447393, 0.62092132,
        0.56447393],
       ...,
       [1.1       , 1.21      , 1.331     , ..., 1.771561  , 1.61051   ,
        1.771561  ],
       [1.1       , 1.21      , 1.331     , ..., 1.771561  , 1.9487171 ,
        1.771561  ],
       [1.1       , 1.21      , 1.331     , ..., 1.771561  , 1.9487171 ,
        2.14358881]])

In [126]:
d2=d1*100
# d2=d1
d2
d3=d2
d3

array([[ 90.90909091,  82.6446281 ,  75.13148009, ...,  56.44739301,
         51.31581182,  46.65073802],
       [ 90.90909091,  82.6446281 ,  75.13148009, ...,  56.44739301,
         51.31581182,  56.44739301],
       [ 90.90909091,  82.6446281 ,  75.13148009, ...,  56.44739301,
         62.09213231,  56.44739301],
       ...,
       [110.        , 121.        , 133.1       , ..., 177.1561    ,
        161.051     , 177.1561    ],
       [110.        , 121.        , 133.1       , ..., 177.1561    ,
        194.87171   , 177.1561    ],
       [110.        , 121.        , 133.1       , ..., 177.1561    ,
        194.87171   , 214.358881  ]])

In [127]:
for j in range(256):
    for i in [6,5,4,3,2,1,0]:
        temp=0
        for t in range(i):
            temp+=d2[j][t]
        d3[j][i]=temp/(i+1)

d3
# d4=d3-d2   
# d4   

array([[  0.        ,  45.45454545,  57.85123967, ...,  63.17977949,
         62.21800999,  46.65073802],
       [  0.        ,  45.45454545,  57.85123967, ...,  63.17977949,
         62.21800999,  56.44739301],
       [  0.        ,  45.45454545,  57.85123967, ...,  63.17977949,
         62.21800999,  56.44739301],
       ...,
       [  0.        ,  55.        ,  77.        , ..., 111.92683333,
        121.2453    , 177.1561    ],
       [  0.        ,  55.        ,  77.        , ..., 111.92683333,
        121.2453    , 177.1561    ],
       [  0.        ,  55.        ,  77.        , ..., 111.92683333,
        121.2453    , 214.358881  ]])